# Generated by Django 6.0.6 on 2026-07-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_patient_profile_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('doctor', 'Doctor'), ('veterinarian', 'Veterinarian'), ('nurse', 'Nurse'), ('staff', 'Staff'), ('patient', 'Patient')], default='patient', max_length=20),
        ),
    ]
