# Generated by Django 6.0.7 on 2026-07-11 12:31

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_time', models.TimeField(default=datetime.time(8, 0), help_text='Clinic opening time (e.g., 08:00)')),
                ('closing_time', models.TimeField(default=datetime.time(17, 0), help_text='Clinic closing time (e.g., 17:00)')),
                ('appointment_duration_minutes', models.PositiveIntegerField(default=30, help_text='Duration of each appointment slot in minutes', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(120)])),
                ('max_appointments_per_day', models.PositiveIntegerField(default=50, help_text='Maximum number of appointments allowed per day')),
                ('max_patients_per_slot', models.PositiveIntegerField(default=1, help_text='Maximum number of patients per time slot', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('cancel_cutoff_hours', models.PositiveIntegerField(default=2, help_text='Hours before appointment when cancellation is no longer allowed')),
                ('operating_days', models.CharField(default='12345', help_text="Days the clinic is open (0=Sun, 1=Mon, ... 6=Sat). E.g., '12345' = weekdays", max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clinic Configuration',
                'verbose_name_plural': 'Clinic Configuration',
                'db_table': 'clinic_configuration',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_phone', models.CharField(max_length=20)),
                ('patient_email', models.EmailField(blank=True, max_length=254)),
                ('appointment_date', models.DateField()),
                ('time_slot', models.CharField(help_text='Format: HH:MM', max_length=5)),
                ('reason', models.CharField(choices=[('new_bite', 'New Animal Bite'), ('follow_up', 'Follow-up Dose'), ('booster', 'Booster'), ('other', 'Other')], max_length=20)),
                ('reason_other', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('rescheduled', 'Rescheduled')], default='pending', max_length=20)),
                ('staff_notes', models.TextField(blank=True, help_text='Internal notes from clinic staff')),
                ('original_date', models.DateField(blank=True, null=True)),
                ('original_time_slot', models.CharField(blank=True, max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'db_table': 'appointments',
                'ordering': ['-appointment_date', 'time_slot'],
                'indexes': [models.Index(fields=['appointment_number'], name='appointment_appoint_e7d91b_idx'), models.Index(fields=['appointment_date', 'time_slot'], name='appointment_appoint_8d1db5_idx'), models.Index(fields=['status'], name='appointment_status_9fecd6_idx'), models.Index(fields=['booked_by'], name='appointment_booked__68a48e_idx')],
                'unique_together': {('booked_by', 'appointment_date', 'time_slot')},
            },
        ),
    ]
