# Generated by Django 6.0.6 on 2026-07-17 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_add_full_workflow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='consultation_report',
        ),
    ]
