# Generated by Django 6.0.7 on 2026-07-11 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('vaccinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinebatch',
            name='reference_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_batches', to='vaccinations.vaccinationrecord'),
        ),
        migrations.AddField(
            model_name='vaccinebatch',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_batches', to='inventory.vaccine'),
        ),
        migrations.AddIndex(
            model_name='vaccinebatch',
            index=models.Index(fields=['batch_number'], name='vaccine_bat_batch_n_ea9606_idx'),
        ),
        migrations.AddIndex(
            model_name='vaccinebatch',
            index=models.Index(fields=['expiration_date'], name='vaccine_bat_expirat_3fd844_idx'),
        ),
    ]
