# Generated by Django 6.0.7 on 2026-07-11 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalBiteCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('incident_date', models.DateTimeField()),
                ('incident_location', models.TextField(blank=True)),
                ('animal_type', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bat', 'Bat'), ('monkey', 'Monkey'), ('rat', 'Rat'), ('other', 'Other')], max_length=20)),
                ('animal_other_type', models.CharField(blank=True, help_text="Specify if animal type is 'other'", max_length=100)),
                ('animal_description', models.TextField(blank=True, help_text='Color, size, distinguishing features')),
                ('animal_owner_name', models.CharField(blank=True, max_length=200)),
                ('animal_owner_contact', models.CharField(blank=True, max_length=20)),
                ('animal_vaccination_status', models.CharField(choices=[('unknown', 'Unknown'), ('vaccinated', 'Vaccinated'), ('not_vaccinated', 'Not Vaccinated'), ('observed', 'Under Observation')], default='unknown', max_length=20)),
                ('animal_is_stray', models.BooleanField(default=False)),
                ('animal_was_provoked', models.BooleanField(blank=True, null=True)),
                ('bite_category', models.CharField(choices=[('I', 'Category I - Animal contact without breaking skin'), ('II', 'Category II - Nibbling without bleeding, scratches without bleeding'), ('III', 'Category III - Single/multiple bites with bleeding, contamination of mucous membrane')], max_length=5)),
                ('exposure_type', models.CharField(choices=[('direct', 'Direct Contact'), ('scratch', 'Scratch'), ('bite', 'Bite'), ('mucous_membrane', 'Mucous Membrane Exposure'), ('other', 'Other')], max_length=20)),
                ('wound_location', models.CharField(choices=[('head', 'Head'), ('face', 'Face'), ('neck', 'Neck'), ('upper_arm', 'Upper Arm'), ('forearm', 'Forearm'), ('hand', 'Hand'), ('finger', 'Finger'), ('chest', 'Chest'), ('abdomen', 'Abdomen'), ('back', 'Back'), ('thigh', 'Thigh'), ('leg', 'Leg'), ('foot', 'Foot'), ('multiple', 'Multiple Locations'), ('other', 'Other')], max_length=20)),
                ('wound_location_other', models.CharField(blank=True, max_length=200)),
                ('wound_description', models.TextField(blank=True)),
                ('wound_depth_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('number_of_wounds', models.IntegerField(default=1)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='mild', max_length=10)),
                ('initial_treatment', models.CharField(choices=[('none', 'No Treatment'), ('wound_cleaning', 'Wound Cleaning'), ('wound_care', 'Wound Care & Dressing'), ('first_aid', 'First Aid'), ('referral', 'Referred for Treatment')], default='none', max_length=20)),
                ('initial_treatment_notes', models.TextField(blank=True)),
                ('wound_treated_within_24h', models.BooleanField(blank=True, null=True)),
                ('tetanus_status_checked', models.BooleanField(default=False)),
                ('tetanus_vaccine_given', models.BooleanField(default=False)),
                ('rabies_immune_globulin_given', models.BooleanField(default=False)),
                ('referred_to_hospital', models.BooleanField(default=False)),
                ('referral_notes', models.TextField(blank=True)),
                ('case_status', models.CharField(choices=[('open', 'Open'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('lost_to_followup', 'Lost to Follow-up'), ('referred', 'Referred')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attending_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attended_cases', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cases', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bite_cases', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Animal Bite Case',
                'verbose_name_plural': 'Animal Bite Cases',
                'db_table': 'animal_bite_cases',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['case_number'], name='animal_bite_case_nu_74c062_idx'), models.Index(fields=['case_status'], name='animal_bite_case_st_3511a3_idx'), models.Index(fields=['bite_category'], name='animal_bite_bite_ca_88c8c7_idx'), models.Index(fields=['incident_date'], name='animal_bite_inciden_673f0b_idx')],
            },
        ),
    ]
