# Generated by Django 6.0.7 on 2026-07-11 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('inventory', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_type', models.CharField(choices=[('first', 'First Dose'), ('second', 'Second Dose'), ('third', 'Third Dose'), ('fourth', 'Fourth Dose'), ('fifth', 'Fifth Dose'), ('booster', 'Booster'), ('tetanus', 'Tetanus Toxoid'), ('rabies_ig', 'Rabies Immune Globulin')], max_length=20)),
                ('dose_number', models.IntegerField(help_text='Sequential dose number for this case')),
                ('scheduled_date', models.DateField()),
                ('administered_date', models.DateField(blank=True, null=True)),
                ('administration_route', models.CharField(choices=[('im', 'Intramuscular (IM)'), ('sc', 'Subcutaneous (SC)'), ('id', 'Intradermal (ID)')], default='im', max_length=5)),
                ('injection_site', models.CharField(blank=True, choices=[('left_deltoid', 'Left Deltoid'), ('right_deltoid', 'Right Deltoid'), ('left_thigh', 'Left Thigh (Anterolateral)'), ('right_thigh', 'Right Thigh (Anterolateral)'), ('left_gluteal', 'Left Gluteal'), ('right_gluteal', 'Right Gluteal')], max_length=20)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('dosage_amount', models.CharField(blank=True, help_text='e.g., 0.5ml, 1.0ml', max_length=50)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('result', models.CharField(choices=[('administered', 'Administered'), ('missed', 'Missed'), ('refused', 'Refused'), ('contraindicated', 'Contraindicated'), ('cancelled', 'Cancelled')], default='administered', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('adverse_reaction', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('administered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_vaccinations', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='cases.animalbitecase')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='patients.patient')),
                ('vaccine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_records', to='inventory.vaccine')),
            ],
            options={
                'verbose_name': 'Vaccination Record',
                'verbose_name_plural': 'Vaccination Records',
                'db_table': 'vaccination_records',
                'ordering': ['-scheduled_date', 'dose_number'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_number', models.IntegerField()),
                ('dose_type', models.CharField(choices=[('first', 'First Dose'), ('second', 'Second Dose'), ('third', 'Third Dose'), ('fourth', 'Fourth Dose'), ('fifth', 'Fifth Dose'), ('booster', 'Booster'), ('tetanus', 'Tetanus Toxoid'), ('rabies_ig', 'Rabies Immune Globulin')], max_length=20)),
                ('scheduled_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_schedule', to='cases.animalbitecase')),
                ('completed_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vaccinations.vaccinationrecord')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_schedules', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Vaccination Schedule',
                'verbose_name_plural': 'Vaccination Schedules',
                'db_table': 'vaccination_schedules',
                'ordering': ['scheduled_date', 'dose_number'],
            },
        ),
        migrations.AddIndex(
            model_name='vaccinationrecord',
            index=models.Index(fields=['patient', 'case'], name='vaccination_patient_d4f92b_idx'),
        ),
        migrations.AddIndex(
            model_name='vaccinationrecord',
            index=models.Index(fields=['scheduled_date'], name='vaccination_schedul_324c37_idx'),
        ),
        migrations.AddIndex(
            model_name='vaccinationrecord',
            index=models.Index(fields=['result'], name='vaccination_result_f7d39f_idx'),
        ),
    ]
